import {prepareImage,resolveImage} from './media.js';
import {setupAccessPanel} from './admin-access-panel.js';
import {normalizeContent,normalizeEvent,normalizeMembership,mergeRows,escapeHTML as h} from './content-model.js';
import {renderEvent} from './content-render.js';
import {setupCertificates} from './certificate-admin.js';
const $=id=>document.getElementById(id), key='acs-editor-draft-v1';
let draft,config,cloud,user,revision=null,canPublish=false,role='',version=0,importCandidate,importVersion,savedDraft=null,sheets=[],selectedEvent='',working=false;
const dirtyForms=new Set();
setupCertificates({getContext:()=>({cloud,user,canPublish,role,enabled:config?.cloudEnabled,archivedGroups:draft?.certificateArchive||[],archiveGroup:(id,hide)=>{if(role!=='super-admin')throw Error('Super-admin access required.');update({...draft,certificateArchive:hide?[...new Set([...(draft.certificateArchive||[]),id])]:(draft.certificateArchive||[]).filter(x=>x!==id)});message('Certificate list updated in your draft. Click Publish website to apply it.');}}),getEvents:()=>draft?.events||[]});
const message=(text,error=false)=>{$('editor-status').textContent=text;$('editor-status').className='editor-status '+(error?'error':'success');let toast=$('editor-toast');if(!toast){toast=document.createElement('div');toast.id='editor-toast';toast.setAttribute('role','status');document.body.append(toast);}toast.textContent=text;toast.className=error?'error':'success';clearTimeout(message.timer);toast.hidden=false;message.timer=setTimeout(()=>toast.hidden=true,9000);};
function controls(){ $('publish-content').disabled=!config?.cloudEnabled||!canPublish||revision===null||working; }
function changed(){version++;controls();$('draft-summary').textContent=`Draft: ${draft.events.length} events, ${draft.team.founders.length} founding members, ${Object.keys(draft.team.committees).length} committee years, ${Object.values(draft.team.committees).reduce((n,c)=>n+c.roster.length,0)} roster members.`;}
function store(){localStorage.setItem(key,JSON.stringify(draft));}
function download(name,value,type){const url=URL.createObjectURL(new Blob([value],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function values(form){return Object.fromEntries(new FormData(form));}
function fill(form,record){for(const field of form.elements){if(!field.name)continue;field.value=Array.isArray(record[field.name])?record[field.name].join('\n'):record[field.name]??'';}if(form.elements.image)updateImagePreview(form.elements.image);}
function showEvent(id){selectedEvent=id;const event=draft.events.find(e=>e.id===id)||{registrationStatus:'unpublished',category:'outreach'};fill($('event-form'),event);$('event-form').elements.id.readOnly=!!id;$('delete-event').disabled=!id;$('event-preview').hidden=true;}
function peopleTable(){const roster=$('people-kind').value==='roster';for(const label of document.querySelectorAll('[data-person-profile]')){label.hidden=roster;label.querySelector('input').disabled=roster;}for(const label of document.querySelectorAll('[data-person-roster]')){label.hidden=!roster;label.querySelector('input,select').disabled=!roster;}$('person-form').elements.memID.required=roster;$('roster-import').hidden=!roster;const kind=$('people-kind').value,year=$('people-year').value;const list=kind==='founders'?draft.team.founders:draft.team.committees[year]?.[kind==='roster'?'roster':'members']||[];$('people-year').disabled=kind==='founders';$('people-table').innerHTML=`<table><thead><tr><th>Name</th>${kind==='roster'?'<th>Membership ID</th>':''}<th>${kind==='roster'?'Tier':'Role'}</th><th>Action</th></tr></thead><tbody>${list.map((m,i)=>`<tr><td>${h(m.name)}</td>${kind==='roster'?`<td>${h(m.memID||'Not recorded')}</td>`:''}<td>${h(m.role||m.tier)}</td><td><button type="button" data-person-edit="${i}" class="secondary">Edit</button> <button type="button" data-person-remove="${i}" class="danger">Remove</button></td></tr>`).join('')||'<tr><td colspan="3">No records for this selection.</td></tr>'}</tbody></table>`;}
function refresh(){const old=selectedEvent;$('event-select').innerHTML='<option value="">New event</option>'+draft.events.map(e=>`<option value="${e.id}">${h(e.title)}</option>`).join('');const selected=role&&role!=='super-admin'?'':draft.events.some(e=>e.id===old)?old:draft.events[0]?.id||'';$('event-select').value=selected;if(!dirtyForms.has('event-form'))showEvent(selected);if(!dirtyForms.has('membership-form'))fill($('membership-form'),draft.membership);peopleTable();if(!dirtyForms.has('homepage-form'))$('homepage-form').elements.images.value=(draft.homepage?.images||[]).join('\n');changed();}
function update(next){draft=normalizeContent(next);changed();try{store();}catch{message('Draft updated, but browser storage is unavailable. Export a content backup.',true);}}
function authError(error){
 const messages={'auth/network-request-failed':'Cannot reach Google/Firebase sign-in. Open this page in Chrome or Edge outside an embedded browser. Check whether a content blocker or network filter blocks identitytoolkit.googleapis.com. Your draft is unchanged.','auth/popup-blocked':'Allow popups for this website and try Sign in with Google again.','auth/popup-closed-by-user':'The sign-in window closed before completion. Choose Sign in with Google to try again.','auth/unauthorized-domain':'This address is not authorized for Google sign-in. Open https://acs-gstu.web.app/admin.html.','auth/operation-not-allowed':'Google sign-in is disabled in Firebase Authentication. Contact the chapter administrator.'};
 return messages[error.code]||error.message||'The action could not be completed.';
}
function on(id,event,fn){$(id).addEventListener(event,async e=>{try{await fn(e);}catch(error){message(authError(error),true);}});}
function discardForms(){if(!dirtyForms.size)return true;if(!confirm('You have unsaved form edits. Discard those edits and continue?'))return false;dirtyForms.clear();fill($('membership-form'),draft.membership);$('person-form').reset();return true;}
document.querySelectorAll('form').forEach(form=>form.addEventListener('input',()=>{dirtyForms.add(form.getAttribute('id'));controls();}));
on('event-select','change',()=>{if(!discardForms()){$('event-select').value=selectedEvent;return;}dirtyForms.clear();showEvent($('event-select').value);});
on('new-event','click',()=>{if(!discardForms())return;dirtyForms.clear();$('event-select').value='';showEvent('');});
on('event-form','submit',async e=>{e.preventDefault();const record=normalizeEvent(values(e.target));if(role&&role!=='super-admin'){await cloud.addEvent(record);const remote=await cloud.read();draft=normalizeContent(remote.content);dirtyForms.delete('event-form');refresh();message('New event published. The action was recorded in the activity log.');return;}if(!selectedEvent&&draft.events.some(item=>item.id===record.id))throw Error('This ID already exists. Select that event to edit it.');const copy=structuredClone(draft);const at=copy.events.findIndex(item=>item.id===selectedEvent);if(at<0)copy.events.push(record);else copy.events[at]=record;update(copy);selectedEvent=record.id;dirtyForms.delete('event-form');refresh();message('Event saved to your browser draft. It is not published yet.');});
on('delete-event','click',()=>{if(!selectedEvent||!confirm('Remove this event from the draft? The live website will change only after publishing.'))return;const copy=structuredClone(draft);copy.events=copy.events.filter(e=>e.id!==selectedEvent);update(copy);selectedEvent='';refresh();message('Event removed from draft.');});
on('preview-event','click',()=>{const event=normalizeEvent(values($('event-form')));$('event-preview').innerHTML=renderEvent({...draft,events:[event]},event.id,{live:true});$('event-preview').hidden=false;});
on('homepage-form','submit',async e=>{e.preventDefault();update({...draft,homepage:{images:values(e.target).images.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)}});dirtyForms.delete('homepage-form');if(role!=='super-admin'){await cloud.publishSection('homepage',draft.homepage);message('Homepage images published.');}else message('Homepage changes saved. Click Publish website to make them live.');});
on('membership-form','submit',async e=>{e.preventDefault();const record=values(e.target);record.benefits=record.benefits.split('\n');update({...draft,membership:normalizeMembership(record)});dirtyForms.delete('membership-form');if(role!=='super-admin'){await cloud.publishSection('membership',draft.membership);message('Membership information published.');}else message('Membership changes saved. Click Publish website to make them live.');});
on('person-form','submit',e=>{e.preventDefault();const row=values(e.target);if(row.kind==='founders')row.year='';update(mergeRows(draft,row.kind,[row]));peopleTable();dirtyForms.delete('person-form');message('Person added or updated in the draft.');});
on('people-kind','change',peopleTable);on('people-year','input',peopleTable);
on('people-table','click',e=>{const edit=e.target.closest('[data-person-edit]'),remove=e.target.closest('[data-person-remove]');if(!edit&&!remove)return;const kind=$('people-kind').value,year=$('people-year').value,copy=structuredClone(draft);const list=kind==='founders'?copy.team.founders:copy.team.committees[year][kind==='roster'?'roster':'members'];const index=Number(edit?.dataset.personEdit??remove.dataset.personRemove);if(edit){fill($('person-form'),{...list[index],kind,year});return;}if(!confirm(`Remove ${list[index].name} from this draft list?`))return;list.splice(index,1);update(copy);peopleTable();message('Person removed from draft.');});
async function xlsx(){if(window.XLSX)return window.XLSX;await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='js/vendor/xlsx.full.min.js';script.onload=resolve;script.onerror=()=>reject(Error('Excel library could not load.'));document.head.append(script);});return window.XLSX;}
const headers={Events:['ID','Title','Date','Category','Image','Description','Location','Registration URL','Registration status','Starts at','Ends at','Source URL'],Committee:['Year','Name','Role','Photo filename'],Roster:['Year','Name','Membership ID','Membership tier'],Founders:['Name','Role','Photo filename']};
async function workbook(template){const X=await xlsx(),book=X.utils.book_new();for(const [name,columns] of Object.entries(headers)){let rows=[];if(!template){if(name==='Events')rows=draft.events.map(e=>[e.id,e.title,e.date,e.category,e.image,e.description,e.location,e.registrationUrl,e.registrationStatus,e.startsAt,e.endsAt,e.sourceUrl]);if(name==='Founders')rows=draft.team.founders.map(m=>[m.name,m.role,m.image]);if(name==='Committee')rows=Object.entries(draft.team.committees).flatMap(([year,c])=>c.members.map(m=>[year,m.name,m.role,m.image]));if(name==='Roster')rows=Object.entries(draft.team.committees).flatMap(([year,c])=>c.roster.map(m=>[year,m.name,m.memID||'',m.tier]));}const sheet=X.utils.aoa_to_sheet([columns,...rows]);sheet['!cols']=columns.map(()=>({wch:25}));X.utils.book_append_sheet(book,sheet,name);}X.writeFile(book,template?'ACS-import-template.xlsx':'ACS-chapter-data.xlsx');}
on('download-template','click',()=>workbook(true));on('export-excel','click',()=>workbook(false));
on('excel-file','change',async()=>{const file=$('excel-file').files[0];importCandidate=null;$('apply-import').disabled=true;$('import-options').hidden=true;$('import-preview').textContent='';if(!file)return;if(file.size>5*1024*1024)throw Error('The workbook must be 5 MB or smaller.');if(!/\.(xlsx|xls|csv)$/i.test(file.name))throw Error('Choose an XLSX, XLS, or CSV file.');message('Reading the workbook on your computer…');const buffer=await file.arrayBuffer();const result=await new Promise((resolve,reject)=>{const worker=new Worker('js/excel-worker.js');const timer=setTimeout(()=>{worker.terminate();reject(Error('Workbook parsing timed out. Try a smaller file.'));},20000);worker.onmessage=e=>{clearTimeout(timer);worker.terminate();e.data.error?reject(Error(e.data.error)):resolve(e.data);};worker.onerror=()=>{clearTimeout(timer);worker.terminate();reject(Error('Workbook could not be read. Check the file format.'));};worker.postMessage({buffer},[buffer]);});sheets=result.sheets;$('import-sheet').innerHTML=sheets.map((s,i)=>`<option value="${i}">${h(s.name)} (${s.rows.length} rows)</option>`).join('');$('import-options').hidden=false;guessSheet();message('Workbook read. Choose a worksheet and review it before applying.');});
function guessSheet(){const name=sheets[Number($('import-sheet').value)]?.name.toLowerCase();if(['events','committee','roster','founders'].includes(name))$('import-kind').value=name;invalidateImport();}
function invalidateImport(){importCandidate=null;$('apply-import').disabled=true;$('import-preview').textContent='';}
on('import-sheet','change',guessSheet);on('import-kind','change',invalidateImport);
on('review-import','click',()=>{const sheet=sheets[Number($('import-sheet').value)];importCandidate=mergeRows(draft,$('import-kind').value,sheet.rows);importVersion=version;const cols=Object.keys(sheet.rows[0]);$('import-preview').innerHTML=`<p>${sheet.rows.length} rows validated. Preview shows the first 20 rows. Unknown columns are ignored; only public names, roles, tiers, image paths, and event fields are imported.</p><table><thead><tr>${cols.map(c=>`<th>${h(c)}</th>`).join('')}</tr></thead><tbody>${sheet.rows.slice(0,20).map(row=>`<tr>${cols.map(c=>`<td>${h(row[c])}</td>`).join('')}</tr>`).join('')}</tbody></table>`;$('apply-import').disabled=false;message('Import validated. Applying changes the browser draft only.');});
on('apply-import','click',()=>{if(!importCandidate||importVersion!==version)throw Error('The draft changed. Review this import again.');if(!discardForms())return;update(importCandidate);dirtyForms.clear();refresh();invalidateImport();message('Reviewed rows applied to the browser draft. Review and publish when ready.');});
on('restore-draft','click',()=>{if(!savedDraft)throw Error('No previous browser draft is available.');if(!confirm('Restore the previous draft? Your current changes will be replaced.'))return;update(savedDraft);dirtyForms.clear();refresh();message('Previous draft restored. Publish website when ready.');});
on('save-draft','click',()=>{store();message('Saved the current draft in this browser. Save any individual form edits before exporting or publishing.');});
on('export-content','click',()=>download('acs-content.json',JSON.stringify(draft,null,2),'application/json'));
on('restore-content','change',async()=>{const file=$('restore-content').files[0];if(!file)return;if(file.size>600000)throw Error('Backup is too large.');const next=normalizeContent(JSON.parse(await file.text()));if(!confirm('Replace the browser draft with this backup? Export your existing draft first if needed.'))return;update(next);dirtyForms.clear();refresh();message('Backup restored to the browser draft.');});

async function activateEditor(account){
 user=account;role=cloud.access?await cloud.access(user):(await cloud.isEditor(user)?'super-admin':'');canPublish=!!role;$('editor-workspace').hidden=!canPublish;
 $('auth-status').textContent=canPublish?'Signed in as '+user.email+'. Role: '+role+'.':'Signed in as '+user.email+'. This account has no publishing access.';
 $('sign-out').hidden=false;$('sign-in').hidden=true;$('load-published').disabled=!canPublish;
 for(const panel of document.querySelectorAll('[data-super-admin]'))panel.hidden=role!=='super-admin';
   $('event-select').hidden=canPublish&&role!=='super-admin';$('delete-event').hidden=role!=='super-admin';
   $('event-form').querySelector('[type="submit"]').textContent=role==='super-admin'?'Save event to draft':'Publish new event';
   for(const link of document.querySelectorAll('.dashboard-sections a'))link.hidden=!!document.querySelector(link.getAttribute('href'))?.hidden;
   window.dispatchEvent(new CustomEvent('editor-role',{detail:role}));
   if(role==='super-admin'){await cloud.ensureSchema?.(draft);if(cloud.manageEditor)setupAccessPanel(cloud);setupSectionToggles();}
   if(canPublish){const remote=await cloud.read();if(remote.content){draft=normalizeContent(remote.content);dirtyForms.clear();refresh();} 
revision=remote.revision;message('Ready. Live content loaded. Save your edits, then click Publish website.');}
 else message('This account has not been granted editor access by the super-admin.',true);controls();
}
on('sign-in','click',async()=>{if(!config)throw Error('Please wait for chapter content to load.');message('Opening Google sign-in…');const {connect}=await import('./cloud-editor.js');cloud=await connect(config.firebase);await activateEditor(await cloud.signIn());});
on('sign-out','click' ,async()=>{await cloud.signOut();user=null;role='';canPublish=false;revision=null;$('editor-workspace').hidden=!!config.cloudEnabled;$('auth-status').textContent='Signed out. Local draft remains in this browser.';$('sign-out').hidden=true;$('sign-in').hidden=false;$('load-published').disabled=true;controls();});
on('load-published','click',async()=>{if(!confirm('Replace the browser draft with published content? Export your current draft first if you need to keep it.'))return;const remote=await cloud.read();revision=remote.revision;update(remote.content||await fetch('data/content.json').then(r=>r.json()));dirtyForms.clear();refresh();message(`Loaded published revision ${revision}.`);});
on('publish-content','click',async()=>{if(!config.cloudEnabled||!canPublish||revision===null)throw Error('Sign in with an authorized account first.');if(dirtyForms.size)throw Error('Save your form edits to the draft before publishing.');if(!confirm('Publish these saved changes to the live website?'))return;working=true;controls();try{draft=normalizeContent(draft);revision=await cloud.publish(draft,revision);try{sessionStorage.removeItem(`acs-content:${config.firebase.projectId}`);}catch{}message(`Published revision ${revision}. The website now uses these records.`);}finally{working=false;controls();}});
try{[config,draft]=await Promise.all([fetch('data/site-config.json').then(r=>r.json()),fetch('data/content.json').then(r=>r.json())]);draft=normalizeContent(draft);let restored=false;try{const saved=localStorage.getItem(key);if(saved){savedDraft=normalizeContent(JSON.parse(saved));if(!config.cloudEnabled)draft=savedDraft;restored=true;}}catch{}refresh();$('editor-workspace').hidden=!!config.cloudEnabled;message(config.cloudEnabled?'Sign in with an authorized chapter account to open the editor.':restored?'Restored your saved browser draft.':'Ready. Live publishing requires the one-time Firebase editor setup; local editing and Excel import work now.');}catch(e){message('Could not load editor content: '+e.message,true);}
window.addEventListener('beforeunload',e=>{if(dirtyForms.size){e.preventDefault();e.returnValue='';}});

// Restore an existing Firebase session without requiring another popup.
if(config?.cloudEnabled){try{const {connect}=await import('./cloud-editor.js');cloud=await connect(config.firebase);const account=await cloud.currentUser?.();if(account)await activateEditor(account);}catch(error){message(authError(error),true);}}
let rosterSheets=[];
async function rosterPreview(){const rows=rosterSheets[Number($('roster-sheet').value)]?.rows||[];$('roster-apply').disabled=true;if(!rows.length)return;const mapped=rows.map((row,i)=>{const fields=Object.fromEntries(Object.entries(row).map(([k,v])=>[k.toLowerCase().replace(/[^a-z]/g,''),String(v).trim()]));const name=fields.membersname||fields.membername||fields.name||fields.fullname,memID=fields.membershipid||fields.memid;if(!name||!memID)throw Error(`Row ${i+2}: Members Name and Membership ID are required.`);return {name,memID,year:$('people-year').value,tier:$('person-form').elements.tier.value};});mergeRows(draft,'roster',mapped);$('roster-preview').innerHTML=`<p>${mapped.length} members for ${h($('people-year').value)} · ${h($('person-form').elements.tier.value)}. First 20 shown:</p><table><thead><tr><th>Name</th><th>Membership ID</th></tr></thead><tbody>${mapped.slice(0,20).map(m=>`<tr><td>${h(m.name)}</td><td>${h(m.memID)}</td></tr>`).join('')}</tbody></table>`;$('roster-apply').disabled=false;return mapped;}
on('roster-template','click',async()=>{const X=await xlsx(),book=X.utils.book_new(),sheet=X.utils.aoa_to_sheet([['Members Name','Membership ID']]);sheet['!cols']=[{wch:35},{wch:25}];X.utils.book_append_sheet(book,sheet,'Members');X.writeFile(book,'ACS-member-template.xlsx');});
on('roster-file','change',async()=>{rosterSheets=[];$('roster-apply').disabled=true;$('roster-preview').textContent='';const file=$('roster-file').files[0];if(!file)return;if(file.size>5*1024*1024||!/\.(xlsx|xls|csv)$/i.test(file.name))throw Error('Choose an XLSX, XLS or CSV file up to 5 MB.');const buffer=await file.arrayBuffer();const result=await new Promise((resolve,reject)=>{const worker=new Worker('js/excel-worker.js'),timer=setTimeout(()=>{worker.terminate();reject(Error('Spreadsheet timed out. Try a smaller file.'));},20000);worker.onmessage=e=>{clearTimeout(timer);worker.terminate();e.data.error?reject(Error(e.data.error)):resolve(e.data);};worker.onerror=()=>{clearTimeout(timer);worker.terminate();reject(Error('Could not read this spreadsheet.'));};worker.postMessage({buffer},[buffer]);});rosterSheets=result.sheets;$('roster-sheet').innerHTML=rosterSheets.map((s,i)=>`<option value="${i}">${h(s.name)}</option>`).join('');$('roster-sheet-label').hidden=rosterSheets.length<2;await rosterPreview();message('Check the member names and IDs below, then click Add these members to changes.');});
on('roster-sheet','change',rosterPreview);on('people-year','change',rosterPreview);$('person-form').elements.tier.addEventListener('change',()=>rosterPreview().catch(e=>message(e.message,true)));
on('roster-apply','click',async()=>{const rows=await rosterPreview();if(!rows?.length)throw Error('Choose a spreadsheet first.');update(mergeRows(draft,'roster',rows));dirtyForms.delete('person-form');peopleTable();$('roster-apply').disabled=true;rosterSheets=[];$('roster-file').value='';message(`${rows.length} members saved to your changes. Click Publish website to make the roster live.`);});

document.addEventListener('invalid',e=>{if(e.target.closest('#editor-workspace'))message('Please complete '+(e.target.closest('label')?.childNodes[0]?.textContent?.trim()||e.target.name)+'. '+e.target.validationMessage,true);},true);

for(const [formID,fieldName,multiple] of [['event-form','image',false],['homepage-form','images',true],['person-form','image',false]]){const field=$(formID).elements[fieldName],label=document.createElement('span');label.className='image-upload';label.textContent='Upload image from your device';const input=document.createElement('input');input.type='file';input.setAttribute('aria-label','Upload image from your device');input.accept='image/jpeg,image/png,image/webp';label.append(input);field.closest('label').append(label);input.addEventListener('change',async()=>{try{if(!cloud||!canPublish)throw Error('Sign in before uploading images.');input.disabled=true;message('Optimizing and uploading image…');const data=await prepareImage(input.files[0]);const reference=await cloud.uploadImage(data,input.files[0].name);field.value=multiple?[field.value.trim(),reference].filter(Boolean).join('\n'):reference;updateImagePreview(field);dirtyForms.add(formID);message('Image uploaded. Save this section to use it.');}catch(error){message(error.message,true);}finally{input.disabled=false;input.value='';}});}

const library=document.createElement('details');library.innerHTML='<summary>Uploaded image library</summary><button type="button" id="refresh-images">Refresh images</button><div id="image-library"></div>';$('homepage-form').after(library);
async function imageLibrary(){if(!cloud?.images)return;const images=await cloud.images();$('image-library').innerHTML=images.length?images.map(img=>`<p>${h(img.name)} <button type="button" data-use-image="${h(img.id)}">Add to homepage</button> <button type="button" data-delete-image="${h(img.id)}" class="danger">Delete unused image</button></p>`).join(''):'<p>No uploaded images yet.</p>';}
on('refresh-images','click',imageLibrary);
on('image-library','click',async e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.useImage){const field=$('homepage-form').elements.images;field.value=[field.value.trim(),'media:'+button.dataset.useImage].filter(Boolean).join('\n');dirtyForms.add('homepage-form');message('Image added. Save homepage changes to use it.');return;}if(button.dataset.deleteImage&&confirm('Permanently delete this unused uploaded image?')){await cloud.deleteImage(button.dataset.deleteImage);await imageLibrary();message('Unused image deleted.');}});

function updateImagePreview(field){
 if(!field)return;const label=field.closest('label');if(!label)return;
 let box=label.querySelector('.uploaded-image-preview');if(!box){box=document.createElement('div');box.className='uploaded-image-preview';label.append(box);}
 const refs=field.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);box.replaceChildren();
 for(const ref of refs){const row=document.createElement('div'),img=document.createElement('img'),note=document.createElement('small');img.width=110;img.height=110;img.alt='Selected image preview';note.textContent=ref.startsWith('media:')?'Uploaded image attached. This reference is managed automatically.':'Selected image';row.append(img,note);box.append(row);resolveImage(ref).then(src=>{if(field.value.includes(ref))img.src=src;}).catch(()=>note.textContent='Image unavailable. Upload it again.');img.onerror=()=>{img.hidden=true;note.textContent='This image path does not exist. Use Upload image from your device.';};}
}
for(const formID of ['person-form','event-form','homepage-form']){const field=$(formID).elements.image||$(formID).elements.images;field.addEventListener('change',()=>updateImagePreview(field));}
function setupSectionToggles(){
 for(const panel of document.querySelectorAll('.editor-panel:not(details)')){const heading=panel.querySelector(':scope > h2');if(!heading||heading.querySelector('.section-toggle'))continue;const title=heading.textContent,button=document.createElement('button'),body=document.createElement('div');body.className='editor-section-body';body.id=(panel.id||'panel-'+Array.from(document.querySelectorAll('.editor-panel')).indexOf(panel))+'-body';button.type='button';button.className='section-toggle';button.setAttribute('aria-label',title);button.setAttribute('aria-expanded','true');button.setAttribute('aria-controls',body.id);button.textContent=title;while(heading.nextSibling)body.append(heading.nextSibling);heading.replaceChildren(button);panel.append(body);button.addEventListener('click',()=>{body.hidden=!body.hidden;button.setAttribute('aria-expanded',String(!body.hidden));});}
}
setupSectionToggles();
document.querySelector('.dashboard-sections')?.addEventListener('click',e=>{const link=e.target.closest('a');if(!link)return;const target=document.querySelector(link.getAttribute('href')),button=target?.querySelector('.section-toggle');if(button?.getAttribute('aria-expanded')==='false')button.click();});
const topLink=document.createElement('a');topLink.href='#main';topLink.className='editor-back-top';topLink.textContent='↑ Back to top';document.body.append(topLink);
