import {categories,escapeHTML as h,eventPast,googleCalendarURL,calendarICS} from './content-model.js';
export const latestYear=data=>Math.max(2024,...data.events.map(e=>Number(e.date.slice(0,4))));
export const eventFile=(data,year,type='all')=>Number(year)===latestYear(data)&&type==='all'?'activities.html':`activities-${year}-${type}.html`;
export const dateLabel=value=>new Date(value+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});
let imageManifest={};
export function useImages(value){imageManifest=value;}
function pagination(items,selected,url,label){const index=items.indexOf(selected);return `<nav class="year-pagination" aria-label="${label}">${index>0?`<a rel="prev" href="${url(items[index-1])}">← Previous</a>`:'<span aria-disabled="true">← Previous</span>'}${items.map(item=>`<a href="${url(item)}"${item===selected?' aria-current="page"':''}>${item==='founders'?'Founding members':item}</a>`).join('')}${index<items.length-1?`<a rel="next" href="${url(items[index+1])}">Next →</a>`:'<span aria-disabled="true">Next →</span>'}</nav>`;}
function photo(src,alt,cls=''){const variants=imageManifest[src];const image=variants?.[Math.min(1,variants.length-1)];return src?`<img class="${cls}" ${src.startsWith('media:')?`data-media="${h(src)}" src="images/brand/acs-symbol.png"`:`src="${h(image?.src||src)}"`} ${variants?`srcset="${[...new Map(variants.map(v=>[v.width,v])).values()].map(v=>`${h(v.src)} ${v.width}w`).join(', ')}" sizes="(max-width: 600px) 100vw, 600px"`:''} alt="${h(alt)}" loading="lazy" decoding="async" width="${image?.width||600}" height="${image?.height||600}">`:'<div class="member-placeholder" aria-hidden="true">ACS</div>';}
export function renderEvents(data,options={}) {
  const year=Number(options.year||latestYear(data)),type=Object.hasOwn(categories,options.type)?options.type:'all';
  const url=(y,t=type)=>options.live?`activities.html?year=${y}&type=${t}`:eventFile(data,y,t);
  const years=[...new Set([2024,2025,2026,year,...data.events.map(e=>Number(e.date.slice(0,4)))])].sort();
  const selected=data.events.filter(e=>Number(e.date.slice(0,4))===year&&(type==='all'||e.category===type)).sort((a,b)=>b.date.localeCompare(a.date));
  return `<section class="archive"><div class="archive-heading"><h6>OUR WORKS AND ACTIVITIES</h6><h1 data-text="ACTIVITY">Our Events</h1></div><nav class="category-tabs" aria-label="Event categories">${Object.entries(categories).map(([key,label])=>`<a href="${url(year,key)}"${key===type?' aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="archive-meta"><h2>${year} <span>/ ${categories[type]}</span></h2><span>${selected.length} events</span></div>${selected.length?`<div class="event-grid">${selected.map(e=>`<a class="event-card" href="${options.live?`event.html?id=${e.id}`:`event-${e.id}.html`}">${photo(e.image,e.title)}<div class="event-card-overlay"><span class="event-kind">${categories[e.category]}</span><h2>${h(e.title)}</h2><time datetime="${e.date}">${dateLabel(e.date)}</time><span class="card-arrow" aria-hidden="true">↗</span></div></a>`).join('')}</div>`:'<div class="empty-state"><h2>Events will be added soon</h2><p>No events have been published in this category for this year.</p><a href="activities.html">View all events →</a></div>'}${pagination(years,year,url,'Event years')}</section>`;
}
export function renderEvent(data,id,{live=false,now=new Date()}={}) {
  const e=data.events.find(e=>e.id===id);
  if(!e)return '<section class="archive"><h1>Event not found</h1><p>This event has not been published, or its address has changed.</p><a href="activities.html">Back to events</a></section>';
  const past=eventPast(e,now);
  const registration=past?'<p class="event-status">This event has ended. Registration is closed.</p>':e.registrationStatus==='open'&&e.registrationUrl?`<a class="button" href="${h(e.registrationUrl)}" target="_blank" rel="noopener noreferrer">Register for this event ↗</a>`:e.registrationStatus==='closed'?'<p class="event-status">Registration is closed.</p>':'<p class="event-status">Registration details will be announced here.</p>';
  const times=e.startsAt?`<dt>Time (Bangladesh)</dt><dd>${h(new Date(e.startsAt).toLocaleString('en-GB',{timeZone:'Asia/Dhaka'}))} – ${h(new Date(e.endsAt).toLocaleString('en-GB',{timeZone:'Asia/Dhaka'}))} (UTC+06:00)</dd>`:'<dt>Time</dt><dd>Time not specified. Calendar links save this as an all-day event.</dd>';
  return `<article class="event-detail"><a class="back-link" href="${live?`activities.html?year=${e.date.slice(0,4)}&type=${e.category}`:eventFile(data,Number(e.date.slice(0,4)),e.category)}">← Back to ${categories[e.category].toLowerCase()} events</a><p class="eyebrow">${categories[e.category]} / ${dateLabel(e.date)}</p><h1>${h(e.title)}</h1><div class="detail-grid">${photo(e.image,e.title,'detail-image')}<div><h2>About the event</h2><p>${h(e.description)}</p><dl><dt>Date</dt><dd><time datetime="${e.date}">${dateLabel(e.date)}</time></dd>${times}<dt>Location</dt><dd>${h(e.location||'Location not published.')}</dd><dt>Organized by</dt><dd>ACS Student Chapter, GSTU</dd></dl>${registration}<div class="event-actions"><a class="button secondary" href="${h(googleCalendarURL(e))}" target="_blank" rel="noopener noreferrer">Google Calendar ↗</a>${live?`<a class="button secondary" href="data:text/calendar;charset=utf-8,${h(encodeURIComponent(calendarICS(e)))}" download="${e.id}.ics">Download calendar (.ics)</a>`:`<a class="button secondary" href="calendar/${e.id}.ics" download>Download calendar (.ics)</a>`}</div>${e.sourceUrl?`<a href="${h(e.sourceUrl)}" target="_blank" rel="noopener noreferrer">View event coverage ↗</a>`:''}</div></div></article>`;
}
function members(list,cls=''){return `<div class="member-grid ${cls}">${list.map(m=>`<article class="member-card">${photo(m.image,m.name)}<div><p>${h(m.role)}</p><h2>${h(m.name)}</h2></div></article>`).join('')}</div>`;}
export function renderTeam(data,{year='founders',live=false}={}) {
  const founding=year==='founders',record=founding?{members:data.team.founders}:data.team.committees[year]||{members:[],roster:[]};
  const title=founding?'Founding Members':`Executive Committee · ${year}`;
  const list=record.members;
  const grid=founding?members(list.filter(m=>/advisor/i.test(m.role)),'founder-advisors')+members(list.filter(m=>/consultant/i.test(m.role)),'founder-consultants')+members(list.filter(m=>!/advisor|consultant/i.test(m.role))):members(list);
  const placeholder=`<p class="placeholder-note">Placeholder committee — official names, roles, and photographs will be added later.</p>${members(['President','Secretary','Outreach Officer'].map(role=>({name:'Name to be added',role:role+' · Placeholder'})))}`;
  const roster=founding?'':`<details class="roster"><summary>Show chapter roster · ${year}<span>General &amp; premium members</span></summary><div class="roster-body">${['general','premium'].map(tier=>`<h3>${tier==='general'?'General':'Premium'} members</h3>${record.roster.some(m=>m.tier===tier)?`<ul>${record.roster.filter(m=>m.tier===tier).map(m=>`<li>${h(m.name)}</li>`).join('')}</ul>`:'<p>No confirmed members for this year yet. The chapter will add its annual roster here.</p>'}`).join('')}</div></details>`;
  const years=['founders',...new Set([...Object.keys(data.team.committees),...(!founding?[year]:[])].sort())];
  return `<section class="archive"><div class="archive-heading"><h6>OUR AMAZING FULLY SKILLED TEAM MEMBERS</h6><h1 data-text="Team">${title}</h1></div>${list.length?grid:placeholder}${roster}${pagination(years,year,y=>live?`team.html?year=${y}`:y==='founders'?'team.html':`team-${y}.html`,'Team archive years')}</section>`;
}
export function renderMembership(data) {
 const m=data.membership;return `<div class="container"><div class="row"><div class="col-12"><h6>Join Us Now!</h6><h2 data-text="Let's Begin">Start your journey with us</h2></div><div class="col-md-5"><h4>Do you want to be a part of our community?</h4><div class="custom-link"><a href="${h(m.applicationUrl||'mailto:'+m.contactEmail)}"><div class="lines"><span></span><span></span></div><b>JOIN NOW</b></a></div></div><div class="col-md-7"><p>${h(m.intro)}</p><details class="home-membership-details"><summary>Membership benefits &amp; renewal</summary><div><h3>Why join?</h3><ul>${m.benefits.map(v=>`<li>${h(v)}</li>`).join('')}</ul><h3>Who can join?</h3><p>${h(m.eligibility)}</p><h3>General membership</h3><p>${h(m.general)}</p><h3>Premium membership</h3><p>${h(m.premium)}</p><h3>Renew your membership</h3><p>${h(m.renewal)}</p><a class="button" href="${h(m.renewalUrl||'mailto:'+m.contactEmail+'?subject=Chapter%20membership%20renewal')}">${m.renewalUrl?'Renew membership ↗':'Ask about renewal'}</a></div></details></div></div></div>`;
}
